package com.studio.visitsukabumi.utils.commons;

/**
 * Created by NwP.
 */
public class Enums {

    public enum APIRoute {
        LOGIN, SIGN_UP, USERS_EDIT, USERS_UPLOAD, USERS_GET,
        UNGGULAN_GET_ALL, AKOMODASI_GET_ALL, OBJEKWISATA_GET_ALL, OBJEKWISATA_GET_ID, TRANSPORTASI_GET_ALL, TRANSPORTASI_GET_ID, SENIBUDAYA_GET_ALL, SENIBUDAYA_GET_ID, PELAYANANPUBLIK_GET_ALL, PELAYANANPUBLIK_GET_ID, RESTORAN_GET_ID, RESTORAN_GET_ALL, BELANJA_GET_ALL, BELANJA_GET_ID, AKTIFITAS_GET_ALL, AKTIFITAS_GET_ID, AKOMODASI_GET_ID
    }

    public enum Menu {
        OBJEK_WISATA, AKOMODASI, SENI_BUDAYA, TEMPAT_MAKAN, BELANJA,
        TRANSPORTASI, AKTIVITAS, TIPS, PELAYANAN_PUBLIK, MAP, EVENT, PROFIL, KONTAK
    }

}
