package com.studio.visitsukabumi.utils.commons;

/**
 * Created by NwP.
 */
public class Enums {

    public enum APIRoute {
        LOGIN, SIGN_UP, USERS_EDIT, USERS_UPLOAD, USERS_GET,
        UNGGULAN_GET_ALL, AKOMODASI_GET_ALL, OBJEKWISATA_GET_ALL, OBJEKWISATA_GET_ID, AKOMODASI_GET_ID
    }

    public enum Menu {
        OBJEK_WISATA, AKOMODASI, SENI_BUDAYA, TEMPAT_MAKAN, BELANJA,
        TRANSPORTASI, KANTOR, PEMERINTAHAN, LAYANAN_PUBLIK, AKTIVITAS, TIPS, PELAYANAN_PUBLIK, MAP, EVENT, PROFIL
    }
}
